port: "8081"
remote_name: "cambridge"

poweronoff_command: "POWER_ONOFF"
poweron_command: "POWERON"
poweroff_command: "POWEROFF"
volumeup_command: "KEY_VOLUMEUP"
volumedown_command: "KEY_VOLUMEDOWN"
sleep_command: "KEY_SLEEP"
mute_command: "KEY_MUTE_UNMUTE"
sourceA1_command: "SOURCE_A1"
sourceA2_command: "SOURCE_A2"
sourceA3_command: "SOURCE_A3"
sourceA4_command: "SOURCE_A4"
sourcecycle_command: "SOURCE_CYCLE"
destA_command: "DEST_A"
destA1_command: "DEST_A1"
destB_command: "DEST_B2"
destB1_command: "DEST_B1"
destB2_command: "DEST_B2"